import "./globals.css";
import localFont from "next/font/local";



const fontB = localFont({
  src: "../public/fonts/puchu2.woff2",
  variable: "--font-b",
});
const fontA = localFont({
  src: "../public/fonts/kuchu1.woff2",
  variable: "--font-a",
});

export const metadata = {
  title: "This is for you my love",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${fontA.variable} ${fontB.variable}`}>
       <body className="font-a ">
        {children}
      </body>
    </html>
  );
}
